# This is a basic workflow to help you get started with Actions

name: Deploying Expense Tracker Applicaton

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploying on surge
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Node.js version 12
        uses: actions/setup-node@v2-beta
        with:
           node-version: 12

      # Runs a set of commands using the runners shell
      - name: Installing surge on server
        run: npm install -g surge
        
      - name: deploying app on server
        run: surge ./ ${{secrets.SURGE_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}
